# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.szs.v2.controllers
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    # path: demo-ui.html            # Swagger UI ?? => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    operations-sorter: alpha      # alpha: ??? ? ?? ??, method: HTTP Method ? ??
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

spring:
  jpa:
    show-sql: true # ?? ?? ??
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # ??? ?? ?? data.sql ??